### ISSUE TITLE
Support arbitrary Zulip instances through custom configuration file

### ISSUE THREAD

**Issue by TheMatten** [srid/zulip-archive#7]
Custom configuration through YAML/TOML/Dhall would make it easy to run archive on arbitrary Zulip instance.

**Comment by srid** [comment]
**Tasks**
- [ ] Configure email and api key via config file
- [ ] Configure instance base url through config file as well
- [ ] Remove `a/user_uploadds` (cf. #1) from git repo, and have the user (optionally) specify its path in the config file

**Comment by srid** [comment]
Fixed in master. (Had to the rebase that PR in order to get rid of uploaded files from git).

**Comment by srid** [comment]
The relevant change: https://github.com/srid/zulip-archive/compare/495ac8a5870540599a7040d4e17b06d95013220f..16be91e893d5ac67925199ce9bd2c9afc59ad3dd
